api:
  url: "https://api.openweathermap.org/data/2.5/weather"
  key: "e54157496385911361b0bb190fb88ef4"
  city: "London"
  interval: 60  # Fetch interval in seconds

kafka:
  bootstrap_servers: "kafka:9092"
  topic: "weather_data"

influxdb:
  url: "http://influxdb:8086"
  token: "L2BZT766lx7qukBxnbScuzF13ZK5UKm_1-WhzVPLUWV28ix4fhgsqGiTx4eQVbgOwRrMFZjiVehNGj_FULlm5Q=="
  org: "weather_data"
  bucket: "weather"

