# Use Python 3.10 slim as the base image
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy necessary files into the container
COPY requirements.txt /app/requirements.txt
COPY flink_data_writer.py /app/flink_data_writer.py
COPY config.yaml /app/config.yaml


# Install Python dependencies
RUN pip install --upgrade pip && pip install -r requirements.txt

# Default command to run the Python script
CMD ["python", "flink_data_writer.py"]
