FROM flink:1.20  

# Install Python 3 and pip
RUN apt-get update && apt-get install -y python3 python3-pip

# Install PyFlink and any other required Python packages
RUN pip3 install apache-flink requests

# Set environment variables
ENV PYTHONPATH=$FLINK_HOME/python:/usr/local/lib/python3.9/site-packages
